### ISSUE TITLE
Enforce the Provider

### ISSUE THREAD

**Issue by danielkcz** [mauricedb/cra-template-mobx-state-tree-typescript#1]
https://github.com/mauricedb/cra-template-mobx-state-tree-typescript/blob/e5735c82fad03b38919a5cc686acd0b6ebfbab0f/template/src/models/useNumbersStore.ts#L8

This is rather bad practice, you are giving the user an idea of false safety that he will always get the correct value. Instead, add a condition and throw an error if nothing is in the Context. TypeScript will then safely narrow that type.

Good job otherwise, looks solid as a template.

**Comment by mauricedb** [comment]
@FredyC I agree, updated the code to:
```
export const useNumbersStore = (): NumbersType => {
  const store = useContext(NumbersStoreContext);
  if (!store) {
    throw new Error(
      "The NumbersStoreContext is not provided using the <NumbersStoreProvider />."
    );
  }
  return store;
};
```
