### ISSUE TITLE
Why the `useObserver`?

### ISSUE THREAD

**Issue by danielkcz** [mauricedb/cra-template-mobx-state-tree-typescript#2]
https://github.com/mauricedb/cra-template-mobx-state-tree-typescript/blob/e5735c82fad03b38919a5cc686acd0b6ebfbab0f/template/src/components/NumbersInfo.tsx#L9

I mean it will work, but the developer might get burned here later when trying to access some observable outside of rendering boundary. I would recommend sticking to `observer` hoc here and later when they know more, they pick correct tools for a particular job.

**Comment by mauricedb** [comment]
@FredyC  Updated to use `observer()` instead.
