### ISSUE TITLE
Don't use index as key

### ISSUE THREAD

**Issue by danielkcz** [mauricedb/cra-template-mobx-state-tree-typescript#3]
https://github.com/mauricedb/cra-template-mobx-state-tree-typescript/blob/e5735c82fad03b38919a5cc686acd0b6ebfbab0f/template/src/components/NumbersList.tsx#L13

In this case, it won't matter, but in my opinion, it shouldn't be showing bad practices like this. Better to teach new people "the correct way" ™.

https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

**Comment by mauricedb** [comment]
@FredyC I completely agree and avoid using the index as key as well. However in the interest of keeping the template simple I didn't want to turn an array of numbers into an array of objects with a key/value pair. However if you prefer that I am happy to do so.

**Comment by danielkcz** [comment]
It's not about what I prefer, but if someone will use it as a teaching material, they might get a bad impression it's the correct approach. I think it's better to show them a better way even if it's more complex. There is tons of basics on the internet, but rarely you find a solutions that go deeper. 

Chances are that people will delete that component after looking at it, so a bit more verbose solution wouldn't be too bad in my opinion. You can even link to that article (or any other) in a comment there because this isn't documented too well in React docs.

So it's either an object solution or might be enough to just generate some random key there. Or you expand the whole idea to unique numbers only and then the number itself can be a key.

**Comment by mauricedb** [comment]
Updated to use a key/value pair and a better `key` in the `<NumbersList/>`
