### ISSUE TITLE
Store should not be instantiated globally

### ISSUE THREAD

**Issue by danielkcz** [mauricedb/cra-template-mobx-state-tree-typescript#4]
https://github.com/mauricedb/cra-template-mobx-state-tree-typescript/blob/e5735c82fad03b38919a5cc686acd0b6ebfbab0f/template/src/App.tsx#L10

Once again it gives bad idea that it's something that's recommended. I mean it works, but in more complex scenarios it can be a foot gun. A developer might be tempted to just export that store and use it directly which doesn't work well when you are writing unit tests and need to reset the state (especially when volatiles are involved).

Besides, it might raise the question of why not set the default value of `createContext` with that instance directly. It's basically the same thing and then you forget about the "checking for null" dance (#1). And you don't even need the Provider, only when writing tests.

**Comment by mauricedb** [comment]
@FredyC Not quite sure what you would like to see here. I need to instantiate the store somewhere to provide it. The best other place I can think of is inside the `NumbersStoreContext.ts` in a more complete `<NumbersStoreProvider/>` component. Or are you looking at another location.

**Comment by danielkcz** [comment]
I think either default value of `createContext` or `const [store] = React.useState(() => NumbersStore.create())` inside the customized Provider component are both good approaches. Choice mostly depends if the store requires some input parameters that might be passed through the Provider props.

**Comment by mauricedb** [comment]
Updated the code to use `useState()`
