### ISSUE TITLE
Separate Provider to its own file

### ISSUE THREAD

**Issue by danielkcz** [mauricedb/cra-template-mobx-state-tree-typescript#5]
https://github.com/mauricedb/cra-template-mobx-state-tree-typescript/blob/5cdacdbccab3ebd8b79bacdb249f6adec18520d4/template/src/models/NumbersStoreContext.tsx#L6

Little nitpick, but I find it a bit weird that contest sits next to models. It might be better to move that to a separate `context` root folder and leave models alone there. You might even go the extra mile and `useNumbersStore.ts` can be in the `hooks` root folder or export that hook from context file itself. I think either helps the separation of concerns.

**Comment by mauricedb** [comment]
Split into multiple folders.
